# Change these first
owner: zootsewt # Your GitHub organization or username, where this repository lives
repo: aistatus # The name of this repository


# Custom user agent
#user-agent: AI Monitor MITRE v0.1.0

# Skip build processes on readme
#skipDescriptionUpdate: true

sites:
  - name: AI For Students
    url: https://www.armyignited.army.mil/student/public/welcome
    method: GET
    __dangerous__insecure: true
  - name: AI For Admin
    url: https://armyignited.army.mil/admin/
    method: GET
    __dangerous__insecure: true
  - name: AI Portal
    url: https://aiportal.army.mil/aiportal/Account/ConsentToMonitor
    method: GET
    __dangerous__insecure: true
  #- name: AI 1.0 (OLD Site)
  #  url: https://www.armyignited.com
  #  __dangerous__insecure: true
  #- name: AI_404
  #  url: https://www.armyignited.army.mil/status
  #  __dangerous__insecure: true
  #- name: Google_Sanity_Check
  #  url: https://www.google.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: aistatus.net
  #baseUrl: /aistatus
  theme: dark
  name: AI Web Status
  introTitle: "**AI Web Response Status**"
  introMessage: This dashboard provides HTTP response status. Overall health of the system (e.g., workflows, data integrity, login functionality) are not included within this status.
  #links:
  #  - rel: stylesheet
  #    href: https://zootsewt.github.io/aistatus/assets/custom-theme.css

  #logoUrl: https://www.armyignited.com/app/assets/img/ignited_lockup_wordmark_inv.svg
  #https://zootsewt.github.io/aistatus/assets/ai.logo.png
#  name: AI monitor
# introTitle: "AI Montior"
# introMessage: AI Monitoring
#  navbar:
#    - title: Status1
#      href: /
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO
#
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration


i18n:
  footer: For illustrative purposes only
  header: For illustrative purposes only
