# Change these first
owner: zootsewt # Your GitHub organization or username, where this repository lives
repo: aistatus # The name of this repository


# Custom user agent
#user-agent: 

# Skip build processes on readme
#skipDescriptionUpdate: true

sites:
  - name: AI For Students
    url: https://www.armyignited.army.mil/student/public/welcome
    method: GET
  #  maxResponseTime: 40000
    __dangerous__insecure: true
  - name: AI For Admin
    url: https://armyignited.army.mil/admin/
    method: GET
  #  maxResponseTime: 40000
    __dangerous__insecure: true
  - name: AI Portal
    url: https://aiportal.army.mil/aiportal/Account/ConsentToMonitor
    method: GET
 #   maxResponseTime: 40000
    __dangerous__insecure: true
#  - name: Ignore this test site
#    url: https://www.google.com/maps.test
#    method: GET 
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: aistatus.net
  #baseUrl: /aistatus
  theme: dark
  name: AI Web Status
  introTitle: "**AI Web Response Status**"
  introMessage: This dashboard provides HTTP response status. Overall health of the system (e.g., workflows, data integrity, login functionality) are not included within this status.



i18n:
  footer: For illustrative purposes only
  header: For illustrative purposes only
